### ISSUE TITLE
Stray causing error when running npm 

### ISSUE THREAD

**Issue by velu76** [laravel-frontend-presets/bulma#22]
There is a stray semicolon at line 210 of file "**_node_modules/bulma-extensions/bulma-calendar/dist/css/bulma-calendar.sass_**"
 
Removing it, causes the error to disappear

**Comment by deeshrestha** [comment]
Let the maintainer fix that or send PR to https://github.com/Wikiki/bulma-calendar

**Comment by deeshrestha** [comment]
Fixed by maintainer

**Comment by deeshrestha** [comment]
Still not fixed

**Comment by TinoN** [comment]
Issue still persists today. (Removal of the ; fixes the issue.)

**Comment by velu76** [comment]
I posted this issue at:
https://github.com/Wikiki/bulma-calendar/issues/129#issue-397211887

For all that still having issues, the follow-up from the above-linked thread instead of here.

**Comment by jhoff** [comment]
[bulma-calendar](https://github.com/Wikiki/bulma-calendar) has been updated with the [fix](https://github.com/Wikiki/bulma-calendar/issues/126) but now [bulma-extensions](https://github.com/Wikiki/bulma-extensions) needs to be updated, as thats the [real dependency](https://github.com/laravel-frontend-presets/bulma/blob/master/src/BulmaPreset.php#L44) being used here.
